# longhorn helm values (base)

# Storage path
defaultSettings:
  defaultDataPath: "/storage"

# Hotfix for Longhorn memory leak
image:
  longhorn:
    manager:
      tag: v1.11.0-hotfix-1
    instanceManager:
      tag: v1.11.0-hotfix-1
