---

- name: Install ddclient
  ansible.builtin.include_tasks: install_ddclient.yml
  args:
    apply:
      become: true

- name: Configure ddclient
  ansible.builtin.include_tasks: configure_ddclient.yml
