apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: haproxy-exporter
spec:
  staticConfigs:
    - targets:
        - service0.${CLUSTER_DOMAIN}:8405
  metricsPath: /metrics