---

# Install python3 pip and virtualenv packages
install_python_packages: true

# Set certbot python virtual environment
certbot_venv: /letsencrypt

# DNS Cloudflare token
cloudflare_api_token: "{{ certmanager_cloudflare_token }}"

certbot_email: "admin@{{ vault.general.domains.dns }}"

# DNS propagation in seconds
propagation_seconds: 300
