---
- hosts: k3s_worker
  become: true
  gather_facts: false
  tasks:
    - name: Reboot agents
      ansible.builtin.reboot:

- hosts: k3s_master
  become: true
  gather_facts: false
  tasks:
    - name: Reboot servers
      ansible.builtin.reboot:

- hosts: service0
  become: true
  gather_facts: false
  tasks:
    - name: Reboot service node
      ansible.builtin.reboot:

- hosts: gateways
  become: true
  gather_facts: false
  tasks:
    - name: Reboot gateways
      ansible.builtin.reboot:
