---
roles:
  - name: willshersystems.sshd
    version: v0.31.0
  - name: ricsanfre.ntp
    version: v1.0.0
  - name: ricsanfre.firewall
    src: https://github.com/olipinski/ansible-role-firewall
    version: main
  - name: mrlesmithjr.netplan
    version: v0.4.2
  - name: ricsanfre.bind9
    src: https://github.com/olipinski/ansible-role-bind9
    version: main
  - name: olipinski.smartd
    version: v1.0.0
  - name: ricsanfre.iscsi_target
    version: v1.0.0
  - name: ricsanfre.iscsi_initiator
    version: v1.1.1
  - name: ricsanfre.k8s_cli
    version: v1.0.0
  - name: ricsanfre.fluentbit
    version: v1.0.5
  - name: ricsanfre.minio
    version: v1.1.15
  - name: ricsanfre.backup
    version: v1.1.3
  - name: ricsanfre.vault
    version: v1.0.5
  - name: geerlingguy.node_exporter
    version: 2.2.0
collections:
  - name: community.general
    version: 12.4.0
  - name: kubernetes.core
    version: 6.3.0
  - name: community.hashi_vault
    version: 7.1.0
  - name: ansible.posix
    version: 2.1.0
  - name: community.crypto
    version: 3.1.1
  - name: kpfleming.systemd_networkd
    version: 26.1.0
